#!/bin/sh
echo "*********************************************************"
echo "  Running git pre-push hook. Running Static analysis...  "
echo "*********************************************************"

./gradlew ktlintCheck --daemon

status=$?

if [ "$status" = 0 ] ; then
    echo "Static analysis found no problems."
    exit 0
else
    echo "************************************************************"
    echo 1>&2 "Static analysis found violations it could not fix."
    echo "Run ./gradlew ktlintFormat to fix formatting related issues."
    echo "************************************************************"
    exit 1
fi